### ISSUE TITLE
What's the license with this?

### ISSUE THREAD

**Issue by wpgaurav** [wpexplorer/office#1]
I mean is this GPL like WP or does it come with Themeforest's Copyright Policy?

**Comment by wpexplorer** [comment]
@wpgaurav - This theme is no longer for sale as it's been deprecated so it now has a full GPL license or a do whatever you want with it license. It's an older theme that could use a lot of love though so I wouldn't really recommend using it but you are welcome to ;)

**Comment by wpgaurav** [comment]
Thank you. Actually I was hoping to dive through the code and features. Open licenses help a lot.
